In [83]:
import pandas as pd
from matplotlib import pyplot
from scipy.stats import shapiro
from mlxtend.preprocessing import minmax_scaling, standardize

df_completa = pd.read_excel("dadosSemDesistentes(Merge).xlsx")

In [110]:
df_completa.head()

,id_aluno,tipo_dica,sexo,nascimento,idade,respondeu_questionario,tp_1,tp_2,tp_3,tp_4,...,n_exercicios_corretos_5,n_exercicios_corretos_6,n_exercicios_corretos_7,total_tempo_ide_1,total_tempo_ide_2,total_tempo_ide_3,total_tempo_ide_4,total_tempo_ide_5,total_tempo_ide_6,total_tempo_ide_7
0,1165,traducao,femi,1997,22,sim,5,5,5,0.00,...,9,10,0,9353,9118,8345,4628,2315,3752,0
1,1330,completa,femi,1997,22,sim,10,10,10,5.00,...,7,7,4,2686,3262,5946,6867,6834,0,3039
2,2171,traducao,masc,1996,23,sim,5,0,0,0.00,...,0,0,0,3659,2492,0,4442,0,0,0
3,3094,completa,masc,1999,20,sim,10,10,10,0.00,...,11,11,5,5592,11219,6508,1544,7588,4398,1672
4,3113,completa,masc,1999,20,sim,10,10,10,3.35,...,12,11,9,4049,10149,25789,18829,17058,4287,9428

In [124]:
def sampleSize(
    population_size=179,
    margin_error=0.05,
    confidence_level=0.95,
    sigma= 8415.713070193115
):
    """
    Calculate the minimal sample size to use to achieve a certain
    margin of error and confidence level for a sample estimate
    of the population mean.
    Inputs
    -------
    population_size: integer
        Total size of the population that the sample is to be drawn from.
    margin_error: number
        Maximum expected difference between the true population parameter,
        such as the mean, and the sample estimate.
    confidence_level: number in the interval (0, 1)
        If we were to draw a large number of equal-size samples
        from the population, the true population parameter
        should lie within this percentage
        of the intervals (sample_parameter - e, sample_parameter + e)
        where e is the margin_error.
    sigma: number
        The standard deviation of the population.  For the case
        of estimating a parameter in the interval [0, 1], sigma=1/2
        should be sufficient.
    """
    alpha = 1 - (confidence_level)
    # dictionary of confidence levels and corresponding z-scores
    # computed via norm.ppf(1 - (alpha/2)), where norm is
    # a normal distribution object in scipy.stats.
    # Here, ppf is the percentile point function.
    zdict = {
        .90: 1.645,
        .91: 1.695,
        .99: 2.576,
        .97: 2.17,
        .94: 1.881,
        .93: 1.812,
        .95: 1.96,
        .98: 2.326,
        .96: 2.054,
        .92: 1.751
    }
    if confidence_level in zdict:
        z = zdict[confidence_level]
    else:
        from scipy.stats import norm
        z = norm.ppf(1 - (alpha/2))
    N = population_size
    M = margin_error
    numerator = z**2 * sigma**2 * (N / (N-1))
    denom = M**2 + ((z**2 * sigma**2)/(N-1))
    return numerator/denom

In [125]:
tps = ['total_tempo_ide_1', 'total_tempo_ide_2', 'total_tempo_ide_3', 'total_tempo_ide_4', 'total_tempo_ide_5', 'total_tempo_ide_6', 'total_tempo_ide_7']
for x in tps:
    print(df_completa[x].std(skipna = True))

4534.361331324178
4119.206076968998
8415.713070193115
6418.001036753168
7482.903738165715
5994.637937404137
6237.55356248896

In [126]:
sampleSize()

178.99999970723508